### ISSUE TITLE
想请教一下如何在这个机型成功安装Big sur

### ISSUE THREAD

**Issue by BakaFT** [VergeDX/Hackintosh_HASEE_ZX6-CT5DA#1]
我使用这个EFI配置引导 20D91 的安装程序会卡在

`console relocated <0x*******>`

目前BIOS没有更新过，只是解锁隐藏选项后关闭了CFG Lock和VT-d，修改了DMVT为64MB。

感谢。

**Comment by VergeDX** [comment]
你可以尝试着去掉一些 “安装时不需要的 Kext”，具体请参考 [OpenCore_Install_Guide](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#kexts)。
我没有刷解锁 BIOS，目前所有的设置都是默认的。

**Comment by BakaFT** [comment]
更新:
使用20C
